Repository Byte-Nova/Rimworld-Together, pull requests merged in 2024-10, with the labels that each got.

#169 Marketplace fixes
  Source/Client/Dialogs/RT_Dialog_1Input.cs
  Source/Client/Dialogs/RT_Dialog_MarketListing.cs
  Source/Client/Managers/DeepScribeManager.cs
  Source/Server/Managers/MarketManager.cs
Labels: needs testing, enhancement

#167 Site Rework
  Builders/Result/3005289691/1.4/Defs/SitePartDefs/SiteParts.xml
  Builders/Result/3005289691/Current/Defs/SitePartDefs/SiteParts.xml
  Builders/Result/3005289691/Current/Textures/Commands/SiteConfig.png
  Builders/Result/3005289691/Current/Textures/Sites/HuntingCamp.png
  Source/Client/Core/Configs/ModStuff.cs
  Source/Client/Dialogs/RT_Dialog_SiteMenu.cs
  Source/Client/Managers/DialogManager.cs
  Source/Client/Managers/GoodwillManager.cs
  Source/Client/Managers/PlanetManager.cs
  Source/Client/Managers/PlayerSiteManager.cs
  Source/Client/Managers/RewardManager.cs
  Source/Client/Managers/RimworldManager.cs
  Source/Client/Managers/SiteManager.cs
  Source/Client/Patches/Pages/WorldViewPatches.cs
  Source/Client/Patches/Tabs/SitesUI.cs
  Source/Server/Core/Main.cs
  Source/Server/Files/UserFile.cs
  Source/Server/Managers/BackupManager.cs
  Source/Server/Managers/FactionManager.cs
  Source/Server/Managers/GlobalDataManager.cs
  Source/Server/Managers/GoodwillManager.cs
  Source/Server/Managers/ResponseShortcutManager.cs
  Source/Server/Managers/RewardManager.cs
  Source/Server/Managers/SaveManager.cs
  Source/Server/Managers/SiteManager.cs
  Source/Server/Managers/Updater/Old Data/OldSites.cs
  Source/Server/Managers/Updater/UpdateManager.cs
  Source/Server/Managers/UserManager.cs
  Source/Server/Misc/Commands/CommandStorage.cs
  Source/Shared/Files/Groups/Sites/SiteConfigFile.cs
  Source/Shared/Files/Groups/Sites/SiteIdendity.cs
  Source/Shared/Files/Groups/Sites/SiteIdendityFile.cs
  Source/Shared/Files/Groups/Sites/SiteInfoFile.cs
  Source/Shared/Files/Groups/Sites/SiteValuesFile.cs
  Source/Shared/Files/SiteValuesFile.cs
  Source/Shared/Files/ThingRewardFile.cs
  Source/Shared/Misc/CommonEnumerators.cs
  Source/Shared/PacketData/RewardData.cs
  Source/Shared/PacketData/ServerGlobalData.cs
  Source/Shared/PacketData/SiteData.cs
  Source/Shared/PacketData/SiteRewardConfig.cs
  Source/Shared/Shared.projitems
Labels: needs: testing, type: enhancement, priority: high

#176 Final fixes Site
  Source/Client/Core/Main.cs
  Source/Client/Managers/SiteManager.cs
  Source/Client/Patches/Pages/CreateWorldParamsPatches.cs
  Source/Client/Values/FactionValues.cs
  Source/Client/Values/ThingDefof.cs
Labels: needs: testing

#180 Egg compatibility
  Source/Client/Managers/DeepScribeManager.cs
  Source/Shared/Files/Components/Thing/EggData.cs
  Source/Shared/Files/ThingDataFile.cs
  Source/Shared/Shared.projitems
Labels: needs: testing

#178 Added support for colored items
  Source/Client/Managers/DeepScribeManager.cs
  Source/Shared/Files/ThingDataFile.cs
Labels: needs: testing

#177 Persona Weapons Compatibility
  Source/Client/Managers/DeepScribeManager.cs
  Source/Shared/Files/Components/Thing/BladelinkWeaponData.cs
  Source/Shared/Files/ThingDataFile.cs
  Source/Shared/Shared.projitems
Labels: needs: testing

#174 Fixed prepatcher
  Source/Client/Core/Configs/Mod.cs
  Source/Client/Core/Main.cs
Labels: needs: testing

#172 Adding new Chat features
  Source/Client/Managers/ChatManager.cs
  Source/Server/Core/Main.cs
  Source/Server/Core/Master.cs
  Source/Server/Files/ChatConfigFile.cs
  Source/Server/Managers/ChatManager.cs
  Source/Server/Managers/LoginManager.cs
  Source/Server/Misc/Commands/CommandStorage.cs
  Source/Server/Network/Network.cs
  Source/Shared/Misc/CommonEnumerators.cs
Labels: needs: testing, type: enhancement

#184 World map pollution sync
  Source/Client/Managers/PollutionManager.cs
  Source/Client/Patches/GameStatusPatches.cs
  Source/Client/Patches/PollutionPatch.cs
  Source/Server/Files/ServerConfigFile.cs
  Source/Server/Managers/NPCSettlementManager.cs
  Source/Server/Managers/PollutionManager.cs
  Source/Shared/Files/ActionValuesFile.cs
  Source/Shared/PacketData/PollutionData.cs
Labels: needs: testing
