Repository Byte-Nova/Rimworld-Together, pull requests merged in 2024-08, with the labels that each got.

#135 XML Parser to handle incorrect casing in about.xml
  Source/Server/Managers/ModManager.cs
  Source/Server/Misc/XmlParser.cs
Labels: bug, enhancement

#139 Discord Integration
  Source/Client/Managers/ChatManager.cs
  Source/Server/Core/Master.cs
  Source/Server/Files/ServerConfigFile.cs
  Source/Server/GameServer.csproj
  Source/Server/Managers/ChatManager.cs
  Source/Server/Managers/DiscordManager.cs
  Source/Server/Managers/ServerCommandManager.cs
  Source/Server/Misc/Logger.cs
  Source/Server/Misc/Threader.cs
  Source/Shared/Misc/CommonEnumerators.cs
Labels: enhancement

#142 Genepacks and Book Sync
  Builder/Deploy Builder.py
  Source/Client/Managers/DeepScribeManager.cs
  Source/Client/Managers/RimworldManager.cs
  Source/Client/Managers/SiteManager.cs
  Source/Client/Managers/TransferManager.cs
  Source/Shared/PacketData/Misc/Transfers/Thing/BookData.cs
  Source/Shared/PacketData/Misc/Transfers/Thing/GenepackData.cs
  Source/Shared/PacketData/Misc/Transfers/Thing/PlantData.cs
  Source/Shared/PacketData/Misc/Transfers/Thing/ThingData.cs
  Source/Shared/PacketData/Misc/Transfers/ThingData.cs
  Source/Shared/Shared.projitems
Labels: enhancement

#129 Multiline Broadcasts
  Source/Client/Managers/ChatManager.cs
  Source/Client/Managers/CommandManager.cs
Labels: needs testing, enhancement, high priority
