Repository Byte-Nova/Rimworld-Together, pull requests merged in 2024-05, with the labels that each got.

#61 Reworked the logger and command manager
  Source/Server/Core/Master.cs
  Source/Server/Managers/Actions/Online/ChatManager.cs
  Source/Server/Managers/Actions/Online/OnlineFactionManager.cs
  Source/Server/Managers/CustomDifficultyManager.cs
  Source/Server/Managers/MapManager.cs
  Source/Server/Managers/ModManager.cs
  Source/Server/Managers/ResponseShortcutManager.cs
  Source/Server/Managers/SaveManager.cs
  Source/Server/Managers/ServerCommandManager.cs
  Source/Server/Managers/SettlementManager.cs
  Source/Server/Managers/SiteManager.cs
  Source/Server/Managers/UserManager.cs
  Source/Server/Managers/WhitelistManager.cs
  Source/Server/Managers/WorldManager.cs
  Source/Server/Misc/Logger.cs
  Source/Server/Misc/XmlParser.cs
  Source/Server/Network/Listener.cs
  Source/Server/Network/Network.cs
  Source/Server/Network/PacketHandler.cs
  Source/Server/Network/UPnP.cs
  Source/Shared/Misc/CommonEnumerators.cs
Labels: question, high priority

#80 Implementation of the logger system to come for the client
  Source/Client/Core/Master.cs
  Source/Client/Core/ModStuff.cs
  Source/Client/Managers/Actions/Offline/OfflineSpyManager.cs
  Source/Client/Managers/Actions/Online/OnlineVisitManager.cs
  Source/Client/Managers/DeepScribeManager.cs
  Source/Client/Managers/DisconnectionManager.cs
  Source/Client/Managers/EventManager.cs
  Source/Client/Managers/PlanetManager.cs
  Source/Client/Managers/SaveManager.cs
  Source/Client/Managers/SiteManager.cs
  Source/Client/Managers/TransferManager.cs
  Source/Client/Managers/WorldGeneratorManager.cs
  Source/Client/Misc/Logger.cs
  Source/Client/Network/Listener.cs
  Source/Client/Network/Network.cs
  Source/Client/Network/PacketHandler.cs
  Source/Client/Patches/SavePatches.cs
Labels: low priority, awaiting

#92 logger-hotfix
  Source/Server/Misc/Logger.cs
Labels: help wanted
